# Generated by Django 2.2.24 on 2023-05-18 10:29

from django.db import migrations
import phonenumbers


def normalize_phone_number(phone_number, region):
    """
    Нормализация телефонного номера по региону
    """
    phone_parts = phonenumbers.parse(phone_number, region)
    if phonenumbers.is_valid_number(phone_parts):
        normalized_phone = f'+{phone_parts.country_code}' \
                           f'{phone_parts.national_number}'
        return normalized_phone


class Migration(migrations.Migration):
    def move_raw_phonenumbers_to_pure_numbers(apps, schema_editor):
        Flat = apps.get_model('property', 'Flat')
        for flat in Flat.objects.all():
            flat.owner_pure_phone = normalize_phone_number(
                flat.owners_phonenumber,
                'RU')
            flat.save()

    def move_backward(apps, schema_editor):
        Flat = apps.get_model('property', 'Flat')
        for flat in Flat.objects.all():
            flat.owners_phonenumber = flat.owner_pure_phone
            flat.save()

    dependencies = [
        ('property', '0002_auto_20230518_1329'),
    ]

    operations = [
        migrations.RunPython(move_raw_phonenumbers_to_pure_numbers, move_backward),
    ]
