# Generated by Django 2.2.24 on 2023-05-16 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flat',
            options={'ordering': ['-created_at']},
        ),
    ]
