# Generated by Django 2.2.24 on 2023-05-18 11:13

from django.db import migrations


class Migration(migrations.Migration):
    def fetch_new_building(apps, schema_editor):
        Flat = apps.get_model('property', 'Flat')
        Flat.objects.filter(construction_year__gte=2015)\
            .update(new_building=True)
        Flat.objects.filter(construction_year__lt=2015) \
            .update(new_building=False)

    def move_backward(apps, schema_editor):
        Flat = apps.get_model('property', 'Flat')
        Flat.objects.all().update(new_building=None)

    dependencies = [
        ('property', '0003_auto_20230518_1329'),
    ]

    operations = [
        migrations.RunPython(fetch_new_building, move_backward),
    ]
