# Generated by Django 2.2.24 on 2023-05-18 12:37

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_update_new_building'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(db_index=True, max_length=250, verbose_name='ФИО владельца')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон', db_index=True)),
                ('pure_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, null=True, region='RU', verbose_name='Телефон (нормализованный)', db_index=True)),
                ('flats', models.ManyToManyField(related_name='owned_by', to='property.Flat', verbose_name='Квартиры')),
            ],
        ),
    ]
