# Generated by Django 2.2.24 on 2023-05-18 13:17

from django.db import migrations


class Migration(migrations.Migration):
    def move_flats_owners_to_owner(apps, schema_editor):
        Flat = apps.get_model('property', 'Flat')
        Owner = apps.get_model('property', 'Owner')
        for flat in Flat.objects.all():
            Owner.objects.get_or_create(
                owner=flat.owner,
                owners_phonenumber=flat.owners_phonenumber,
                owner_pure_phone=flat.owner_pure_phone
            )

    def move_backward(apps, schema_editor):
        Owner = apps.get_model('property', 'Owner')
        Owner.objects.all().update(
            owner=None,
            owners_phonenumber=None,
            owner_pure_phone=None
        )

    dependencies = [
        ('property', '0005_owner'),
    ]

    operations = [
        migrations.RunPython(move_flats_owners_to_owner, move_backward),
    ]
