# Generated by Django 2.2.24 on 2023-05-18 13:17

from django.db import migrations, connection, reset_queries
from django.core.paginator import Paginator


def num_queries(reset=True):
    print(len(connection.queries))
    if reset:
        reset_queries()


class Migration(migrations.Migration):
    def migrate_flats_owners_to_owner(apps, schema_editor):
        Flat = apps.get_model('property', 'Flat')
        Owner = apps.get_model('property', 'Owner')
        owners = Owner.objects.all()

        flats = Flat.objects.all()
        flats_paginator = Paginator(flats, 1000)

        for page_number in flats_paginator.page_range:
            page = flats_paginator.page(page_number)

            for item in page.object_list:
                owner, created = owners.get_or_create(
                    owner=item.owner,
                    phone=item.owners_phonenumber,
                    pure_phone=item.owner_pure_phone,
                )
                owner.flats.add(item)

        num_queries()

    def migrate_backward(apps, schema_editor):
        Owner = apps.get_model('property', 'Owner')
        owners = Owner.objects.all()
        owners_paginator = Paginator(owners, 1000)
        for page_number in owners_paginator.page_range:
            page = owners_paginator.page(page_number)
            for item in page.object_list:
                item.flats.clear()
        num_queries()

    dependencies = [
        ('property', '0005_owner'),
    ]

    operations = [
        migrations.RunPython(
            migrate_flats_owners_to_owner,
            migrate_backward
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owners_phonenumber',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owner_pure_phone',
        ),
    ]
